language: python

python:
  - "2.7"

install:
  - pip install -r requirements-dev.txt

script:
  - flake8 --max-line-length 124 app.py

before_deploy:
  - perl -i -pe 's/@@(.*)@@/$ENV{$1}/eg' app.py # Substitute configuration from the environment.

deploy:
  provider: script
  script: chalice deploy
  skip_cleanup: true
  on:
    branch: master
