language: python

python:
  - "2.7"

install:
  - pip install -r requirements-dev.txt

script:
  - flake8 app.py
  
before_deploy:
  - sed --quiet --in-place "s/@@FIREBASE_DATABASE_SECRET@@/${FIREBASE_DATABASE_SECRET}/g" app.py
  - sed --quiet --in-place "s/@@FIREBASE_SERVER_KEY@@/${FIREBASE_SERVER_KEY}/g" app.py

deploy:
  provider: script
  script: chalice deploy
  skip_cleanup: true
  on:
    branch: master
